"""
src/distillation/teacher_student.py
Phase 2b — Knowledge distillation: Hermes-4.3-36B teacher → Hermes-3-8B student.

Key constraint (VLA-JEPA principle):
  Student sees ONLY current observation — future frames used as supervision targets only.
  No information leakage from future frames into student input.

Strategy:
  1. Generate annotated trajectories with 36B teacher (offline)
  2. Fine-tune 8B student on teacher outputs (token-level KD + trajectory matching)
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.optim import AdamW
from torch.utils.data import DataLoader, Dataset

from src.utils import (
    StepTimer,
    get_logger,
    seed_everything,
)


# ─── Config ───────────────────────────────────────────────────────────────────

@dataclass
class DistillationConfig:
    # Teacher: Hermes-4.3-36B + LoRA adapter from Phase 2
    # Runs on A100 80GB for trajectory generation (offline)
    teacher_model_id: str = "NousResearch/Hermes-4.3-36B"
    teacher_lora_checkpoint: str = ""     # Phase 2 LoRA adapter checkpoint
    teacher_device: str = "cuda"          # A100 80GB

    # Student: Hermes-3-8B → edge deployment target
    # Trains on RTX 4090 24GB (~6GB QLoRA VRAM)
    student_model_id: str = "NousResearch/Hermes-3-Llama-3.1-8B"
    student_checkpoint: str = ""          # Optional starting checkpoint
    output_dir: str = "experiments/phase2b"

    # Distillation data (generated by teacher offline)
    teacher_trajectories_path: str = "data/teacher_trajectories.jsonl"
    n_trajectories: int = 500

    # Student QLoRA (RTX 4090, very comfortable at ~6GB)
    use_qlora: bool = True
    qlora_bits: int = 4
    qlora_r: int = 16
    qlora_alpha: int = 32

    # Training
    batch_size: int = 8
    lr: float = 2e-5
    weight_decay: float = 1e-4
    n_epochs: int = 3
    max_seq_len: int = 1024
    temperature: float = 2.0              # KD temperature
    alpha_ce: float = 0.5
    alpha_kd: float = 0.5
    gradient_checkpointing: bool = True
    device: str = "cuda"
    seed: int = 42
    available_vram_gb: float = 24.0       # RTX 4090 for student training


# ─── Trajectory generation (teacher) ─────────────────────────────────────────

@dataclass
class RobotTrajectory:
    """A single teacher-annotated robot trajectory."""
    task_instruction: str
    world_state_description: str
    reasoning: str                        # Teacher's <think> block
    action_sequence: list[dict]           # List of tool calls
    success: bool
    metadata: dict = field(default_factory=dict)


def generate_teacher_trajectories(
    config: DistillationConfig,
    task_scenarios: list[dict],
    logger: Optional[logging.Logger] = None,
) -> list[RobotTrajectory]:
    """
    Generate annotated trajectories using Hermes-4.3-36B teacher + Phase 2 LoRA adapter.

    Runs on A100 80GB (cloud). Saves to JSONL for offline student training.
    Teacher = Hermes-4.3-36B base + LoRA adapter fine-tuned in Phase 2 (VLA robotics).

    Args:
        config: DistillationConfig
        task_scenarios: List of dicts with 'instruction' and 'world_state'
        logger: Optional logger

    Returns:
        List of RobotTrajectory objects.
    """
    if logger is None:
        logger = get_logger(__name__)

    from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
    from peft import PeftModel
    from src.pipeline.hermes_vla import format_tool_call_prompt

    logger.info(f"Loading teacher: {config.teacher_model_id}")

    # Load base model in 4-bit NF4 (same as training)
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16,
        bnb_4bit_use_double_quant=True,
    )
    tokenizer = AutoTokenizer.from_pretrained(config.teacher_model_id, trust_remote_code=True)
    teacher_base = AutoModelForCausalLM.from_pretrained(
        config.teacher_model_id,
        quantization_config=bnb_config,
        device_map="auto",
        trust_remote_code=True,
    )

    # Load Phase 2 LoRA adapter on top
    if config.teacher_lora_checkpoint:
        logger.info(f"Loading Phase 2 LoRA adapter from {config.teacher_lora_checkpoint}")
        teacher = PeftModel.from_pretrained(teacher_base, config.teacher_lora_checkpoint)
        logger.info("LoRA adapter loaded — teacher is Phase-2 fine-tuned Hermes-4.3-36B")
    else:
        logger.warning(
            "No teacher_lora_checkpoint provided — using base Hermes-4.3-36B without Phase 2 fine-tuning. "
            "Trajectory quality will be lower."
        )
        teacher = teacher_base

    teacher.eval()

    trajectories: list[RobotTrajectory] = []
    output_path = Path(config.teacher_trajectories_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    logger.info(f"Generating {len(task_scenarios)} teacher trajectories with <think> reasoning...")

    with output_path.open("w") as f_out:
        for i, scenario in enumerate(task_scenarios):
            # Enable thinking mode for richer reasoning traces
            prompt = format_tool_call_prompt(
                instruction=scenario["instruction"],
                world_state_description=scenario["world_state"],
                tokenizer=tokenizer,
                enable_thinking=True,  # Hermes-4.3-36B hybrid reasoning
            )

            inputs = tokenizer(prompt, return_tensors="pt").to(teacher.device)

            with torch.no_grad():
                output_ids = teacher.generate(
                    **inputs,
                    max_new_tokens=512,
                    temperature=0.6,
                    top_p=0.95,
                    top_k=20,
                    do_sample=True,
                )

            response = tokenizer.decode(
                output_ids[0][inputs["input_ids"].shape[1]:],
                skip_special_tokens=False,
            )

            reasoning, actions = _parse_teacher_response(response)

            traj = RobotTrajectory(
                task_instruction=scenario["instruction"],
                world_state_description=scenario["world_state"],
                reasoning=reasoning,
                action_sequence=actions,
                success=len(actions) > 0,
                metadata={
                    "scenario_id": i,
                    "teacher": config.teacher_model_id,
                    "lora_checkpoint": config.teacher_lora_checkpoint,
                },
            )
            trajectories.append(traj)

            f_out.write(json.dumps(traj.__dict__) + "\n")
            f_out.flush()

            if (i + 1) % 50 == 0:
                success_rate = sum(1 for t in trajectories if t.success) / len(trajectories)
                logger.info(
                    f"Generated {i+1}/{len(task_scenarios)} trajectories "
                    f"(success rate: {success_rate:.1%})"
                )

    logger.info(f"Saved trajectories → {output_path}")
    return trajectories


def _parse_teacher_response(response: str) -> tuple[str, list[dict]]:
    """Extract <think>...</think> reasoning and <tool_call>...</tool_call> blocks."""
    import re

    # Extract reasoning
    think_match = re.search(r"<think>(.*?)</think>", response, re.DOTALL)
    reasoning = think_match.group(1).strip() if think_match else ""

    # Extract tool calls
    tool_calls = []
    for match in re.finditer(r"<tool_call>(.*?)</tool_call>", response, re.DOTALL):
        try:
            tool_call = json.loads(match.group(1).strip())
            tool_calls.append(tool_call)
        except json.JSONDecodeError:
            pass

    return reasoning, tool_calls


# ─── Dataset ──────────────────────────────────────────────────────────────────

class TrajectoryDataset(Dataset):
    """Dataset of teacher-annotated trajectories for student distillation."""

    def __init__(
        self,
        trajectories_path: str,
        tokenizer,
        max_seq_len: int = 1024,
    ) -> None:
        self.tokenizer = tokenizer
        self.max_seq_len = max_seq_len
        self.samples: list[dict] = []

        with open(trajectories_path) as f:
            for line in f:
                traj = json.loads(line.strip())
                if traj.get("success", False):  # Only use successful trajectories
                    self.samples.append(traj)

    def __len__(self) -> int:
        return len(self.samples)

    def __getitem__(self, idx: int) -> dict:
        sample = self.samples[idx]

        # Build training text: instruction → reasoning → actions
        # Leakage-free: student input is ONLY current observation (no future frames)
        text = (
            f"<|im_start|>system\n"
            f"You are a robotic planning agent. Current world state: "
            f"{sample['world_state_description']}<|im_end|>\n"
            f"<|im_start|>user\n{sample['task_instruction']}<|im_end|>\n"
            f"<|im_start|>assistant\n"
            f"<think>{sample['reasoning']}</think>\n"
        )

        # Add action sequence as tool calls
        for action in sample["action_sequence"]:
            text += f"<tool_call>{json.dumps(action)}</tool_call>\n"
        text += "<|im_end|>"

        tokens = self.tokenizer(
            text,
            max_length=self.max_seq_len,
            truncation=True,
            padding="max_length",
            return_tensors="pt",
        )

        input_ids = tokens["input_ids"].squeeze(0)
        attention_mask = tokens["attention_mask"].squeeze(0)

        # Labels: -100 for padding, actual ids for completion tokens
        labels = input_ids.clone()
        labels[attention_mask == 0] = -100

        return {
            "input_ids": input_ids,
            "attention_mask": attention_mask,
            "labels": labels,
        }


# ─── KD loss ──────────────────────────────────────────────────────────────────

def knowledge_distillation_loss(
    student_logits: torch.Tensor,
    teacher_logits: torch.Tensor,
    labels: torch.Tensor,
    temperature: float = 2.0,
    alpha_ce: float = 0.5,
    alpha_kd: float = 0.5,
) -> tuple[torch.Tensor, dict[str, float]]:
    """
    Standard knowledge distillation loss: CE on hard labels + KL on soft distributions.

    Args:
        student_logits: [B, T, V]
        teacher_logits: [B, T, V] — stop gradient
        labels: [B, T] hard labels (with -100 for ignored positions)
        temperature: Softmax temperature for KD
        alpha_ce / alpha_kd: Loss weights

    Returns:
        (total_loss, metrics_dict)
    """
    # Hard label CE loss
    ce_loss = F.cross_entropy(
        student_logits.view(-1, student_logits.size(-1)),
        labels.view(-1),
        ignore_index=-100,
    )

    # Soft KD loss (only on non-ignored positions)
    mask = (labels != -100).view(-1)
    if mask.sum() == 0:
        kd_loss = torch.tensor(0.0, device=student_logits.device)
    else:
        s_log_probs = F.log_softmax(student_logits.view(-1, student_logits.size(-1))[mask] / temperature, dim=-1)
        t_probs = F.softmax(teacher_logits.detach().view(-1, teacher_logits.size(-1))[mask] / temperature, dim=-1)
        kd_loss = F.kl_div(s_log_probs, t_probs, reduction="batchmean") * (temperature ** 2)

    total = alpha_ce * ce_loss + alpha_kd * kd_loss

    return total, {
        "loss/total": total.item(),
        "loss/ce": ce_loss.item(),
        "loss/kd": kd_loss.item(),
    }


# ─── Student trainer ──────────────────────────────────────────────────────────

class StudentDistillationTrainer:
    """
    Fine-tune Hermes-3-8B student on Phase-2 teacher trajectories.

    Hardware: RTX 4090 24GB (Vast.ai ~$0.4/h)
    VRAM: ~6GB for Hermes-3-8B QLoRA — very comfortable on RTX 4090.
    """

    def __init__(
        self,
        config: DistillationConfig,
        logger: Optional[logging.Logger] = None,
    ) -> None:
        from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
        from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

        self.cfg = config
        self.logger = logger or get_logger(__name__)
        self.device = torch.device(config.device if torch.cuda.is_available() else "cpu")
        self.output_dir = Path(config.output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

        seed_everything(config.seed)

        self.logger.info(
            f"Loading student: {config.student_model_id} "
            f"(QLoRA 4-bit, RTX 4090 ~6GB VRAM)"
        )
        self.tokenizer = AutoTokenizer.from_pretrained(
            config.student_model_id, trust_remote_code=True
        )
        self.tokenizer.pad_token = self.tokenizer.eos_token

        if config.use_qlora:
            bnb_config = BitsAndBytesConfig(
                load_in_4bit=True,
                bnb_4bit_quant_type="nf4",
                bnb_4bit_compute_dtype=torch.bfloat16,
                bnb_4bit_use_double_quant=True,
            )
            student_base = AutoModelForCausalLM.from_pretrained(
                config.student_model_id,
                quantization_config=bnb_config,
                device_map="auto",
                trust_remote_code=True,
            )
            student_base = prepare_model_for_kbit_training(
                student_base,
                use_gradient_checkpointing=config.gradient_checkpointing,
            )
            lora_config = LoraConfig(
                r=config.qlora_r,
                lora_alpha=config.qlora_alpha,
                target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                                 "gate_proj", "up_proj", "down_proj"],
                bias="none",
                task_type="CAUSAL_LM",
            )
            self.student = get_peft_model(student_base, lora_config)
            self.student.print_trainable_parameters()
        else:
            self.student = AutoModelForCausalLM.from_pretrained(
                config.student_model_id,
                torch_dtype=torch.bfloat16,
                device_map="auto",
                trust_remote_code=True,
            )
            if config.gradient_checkpointing:
                self.student.gradient_checkpointing_enable()

        dataset = TrajectoryDataset(
            config.teacher_trajectories_path,
            self.tokenizer,
            max_seq_len=config.max_seq_len,
        )
        self.dataloader = DataLoader(
            dataset,
            batch_size=config.batch_size,
            shuffle=True,
            num_workers=2,
            pin_memory=True,
        )

        self.optimizer = AdamW(
            filter(lambda p: p.requires_grad, self.student.parameters()),
            lr=config.lr,
            weight_decay=config.weight_decay,
        )

    def train(self) -> None:
        self.logger.info(
            f"Phase 2b — Distillation: Hermes-4.3-36B → Hermes-3-8B "
            f"({self.cfg.n_epochs} epochs, RTX 4090)"
        )
        step = 0

        for epoch in range(self.cfg.n_epochs):
            self.logger.info(f"\nEpoch {epoch+1}/{self.cfg.n_epochs}")
            self.student.train()

            for batch in self.dataloader:
                input_ids = batch["input_ids"].to(self.device)
                attention_mask = batch["attention_mask"].to(self.device)
                labels = batch["labels"].to(self.device)

                with StepTimer(step, log_every=50, logger=self.logger):
                    outputs = self.student(
                        input_ids=input_ids,
                        attention_mask=attention_mask,
                        labels=labels,
                    )
                    loss = outputs.loss
                    self.optimizer.zero_grad()
                    loss.backward()
                    nn.utils.clip_grad_norm_(
                        filter(lambda p: p.requires_grad, self.student.parameters()),
                        max_norm=1.0,
                    )
                    self.optimizer.step()

                if step % 50 == 0:
                    self.logger.info(f"step={step}  loss={loss.item():.4f}")

                step += 1

        # Save LoRA adapter (small, ~100-500MB)
        adapter_path = self.output_dir / "student_lora_adapter"
        self.student.save_pretrained(adapter_path)
        self.tokenizer.save_pretrained(adapter_path)
        self.logger.info(f"LoRA adapter saved → {adapter_path}")

        # Merge LoRA into base weights for clean GGUF export
        self.logger.info("Merging LoRA adapters into base weights (needed for GGUF export)...")
        try:
            merged = self.student.merge_and_unload()
            merged_path = self.output_dir / "student_merged"
            merged.save_pretrained(merged_path, safe_serialization=True)
            self.tokenizer.save_pretrained(merged_path)
            self.logger.info(
                f"Merged student saved → {merged_path}\n"
                f"Ready for GGUF conversion: "
                f"python llama.cpp/convert_hf_to_gguf.py {merged_path} --outtype f16"
            )
        except Exception as e:
            self.logger.warning(
                f"Merge failed ({e}). Use LoRA adapter directly with PEFT. "
                f"GGUF export requires manual merge."
            )
